### ISSUE TITLE
just wondering why new seed after snapshot

### ISSUE THREAD

**Issue by wonkytonky** [peterwilli/IOTA-Snapshot-Recovery#2]
shouldn't be  an old seed  still be secure after a snapshot?
or is it just  to  be extra safe you create new seed..?

**Comment by rajivshah3** [comment]
It’s so that you don’t need to generate a ton of addresses in the wallet

**Comment by peterwilli** [comment]
@rajivshah3 is right. The idea is that you don't want a seed that needs to generated like 1000 addresses, because that is what this tool is doing. The new seed gives you quick access to a post-snapshot wallet without any delay.
