### ISSUE TITLE
PR with IOTA-Balance Finder?

### ISSUE THREAD

**Issue by peterwilli** [peterwilli/IOTA-Snapshot-Recovery#3]
Hi @rajivshah3! I was wondering if you could send a PR our way? So we can build on your fantastic fork? Thanks!

**Comment by rajivshah3** [comment]
Sure! I’d be happy to

**Comment by rajivshah3** [comment]
If you want a browserified version I think @cyclux was able to get it to work

**Comment by peterwilli** [comment]
Thanks! I'll make sure this get's included
